# Generated by Django 2.1.1 on 2020-09-27 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity_type', models.CharField(choices=[('class', '考勤'), ('activity', '活动')], default='class', max_length=20, verbose_name='活动类型')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('status', models.CharField(choices=[('preview', '预览'), ('release', '发布')], default='preview', max_length=20, verbose_name='活动状态')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=30, verbose_name='班级名称')),
                ('sharecode', models.CharField(default=manage.models.class_hash, max_length=10, unique=True, verbose_name='访问码')),
                ('managecode', models.CharField(max_length=20, verbose_name='管理密码')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('absent', '缺席'), ('late', '迟到'), ('leave', '请假'), ('present', '正常')], default='present', max_length=20, verbose_name='考勤状态')),
                ('level', models.CharField(choices=[('none', '未参加'), ('low', '班级'), ('mid', '院级'), ('high', '校级')], default='none', max_length=20, verbose_name='参与情况')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=8, verbose_name='性别')),
                ('inclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Class')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SummaryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020, verbose_name='年')),
                ('month', models.IntegerField(default=9, verbose_name='月')),
                ('absent_count', models.IntegerField(default=0, verbose_name='缺勤次数')),
                ('late_count', models.IntegerField(default=0, verbose_name='迟到次数')),
                ('leave_count', models.IntegerField(default=0, verbose_name='请假次数')),
                ('low_count', models.IntegerField(default=0, verbose_name='一般活动次数')),
                ('mid_count', models.IntegerField(default=0, verbose_name='中级活动次数')),
                ('high_count', models.IntegerField(default=0, verbose_name='重要活动次数')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Student')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Class'),
        ),
    ]
