# Generated by Django 2.1.1 on 2020-09-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='discipline',
            field=models.CharField(choices=[('none', '正常'), ('low', '轻度违纪'), ('mid', '中度违纪'), ('high', '严重违纪')], default='none', max_length=20, verbose_name='违纪情况'),
        ),
        migrations.AddField(
            model_name='summarycount',
            name='discipline_high_count',
            field=models.IntegerField(default=0, verbose_name='严重违纪次数'),
        ),
        migrations.AddField(
            model_name='summarycount',
            name='discipline_low_count',
            field=models.IntegerField(default=0, verbose_name='轻度违纪次数'),
        ),
        migrations.AddField(
            model_name='summarycount',
            name='discipline_mid_count',
            field=models.IntegerField(default=0, verbose_name='中度违纪次数'),
        ),
    ]
