# Generated by Django 5.2.17 on 2026-09-22 22:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manage.models
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password
from django.db.models import Count, F


def preflight(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name, fields in [('Student', ['inclass', 'number']), ('Report', ['activity', 'student']), ('SummaryCount', ['student', 'year', 'month'])]:
        model = apps.get_model('manage', name)
        count = model.objects.using(alias).values(*fields).annotate(n=Count('id')).filter(n__gt=1).count()
        if count:
            raise RuntimeError(f'Migration blocked: {name} has {count} duplicate groups. Review before applying constraints.')
    Report = apps.get_model('manage', 'Report')
    if Report.objects.using(alias).exclude(activity__inclass_id=F('student__inclass_id')).exists():
        raise RuntimeError('Migration blocked: cross-class reports require review.')


def preserve_legacy(apps, schema_editor):
    alias = schema_editor.connection.alias
    Class = apps.get_model('manage', 'Class')
    Activity = apps.get_model('manage', 'Activity')
    for classroom in Class.objects.using(alias).all().iterator():
        classroom.managecode = make_password(classroom.managecode or None)
        classroom.legacy_pending = True
        classroom.save(using=alias, update_fields=['managecode', 'legacy_pending'])
    for activity in Activity.objects.using(alias).all().iterator():
        Activity.objects.using(alias).filter(pk=activity.pk).update(occurred_on=activity.time.date())



class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_auto_20200927_0028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_id', models.PositiveIntegerField(null=True)),
                ('kind', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=240)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('revision', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassDailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('created_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_key', models.CharField(max_length=20)),
                ('archived_data', models.JSONField(null=True)),
                ('baseline_source', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerScoringSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerTermPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RosterVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_term_start', models.DateField()),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringPolicyVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_term_start', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('algorithm', models.CharField(default='calendar-month-v1', max_length=30)),
                ('absent', models.DecimalField(decimal_places=2, default=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('late', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('leave', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid', models.DecimalField(decimal_places=2, default=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.DecimalField(decimal_places=2, default=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('dlow', models.DecimalField(decimal_places=2, default=5, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('dmid', models.DecimalField(decimal_places=2, default=8, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('dhigh', models.DecimalField(decimal_places=2, default=12, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_key', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=80)),
                ('key', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-occurred_on', '-id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number', 'id']},
        ),
        migrations.AddField(
            model_name='activity',
            name='occurred_on',
            field=models.DateField(default=manage.models.local_date, verbose_name='发生日期'),
        ),
        migrations.AddField(
            model_name='activity',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='grant_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class',
            name='legacy_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class',
            name='started_on',
            field=models.DateField(default=manage.models.local_date),
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('class', '考勤'), ('activity', '活动'), ('discipline', '违纪')], default='class', max_length=20, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='managecode',
            field=models.CharField(max_length=128, verbose_name='班级密码散列'),
        ),
        migrations.AlterField(
            model_name='class',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='absent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='discipline_high_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='discipline_low_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='discipline_mid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='high_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='late_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='low_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='mid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarycount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.student'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['inclass', 'occurred_on'], name='activity_class_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('activity', 'student'), name='report_activity_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('inclass', 'number'), name='student_class_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='summarycount',
            constraint=models.UniqueConstraint(fields=('student', 'year', 'month'), name='summary_student_month_unique'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AddField(
            model_name='classdailyusage',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AddField(
            model_name='classterm',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AddField(
            model_name='classterm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerscoringsettings',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownertermpolicy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosterversion',
            name='inclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AddField(
            model_name='rosterversion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.student'),
        ),
        migrations.AddField(
            model_name='scoringpolicyversion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownertermpolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage.scoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='ownerscoringsettings',
            name='default_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manage.scoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='classterm',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manage.scoringpolicyversion'),
        ),
        migrations.AddField(
            model_name='submission',
            name='inclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manage.class'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['inclass', 'created_at'], name='event_class_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='classdailyusage',
            constraint=models.UniqueConstraint(fields=('inclass', 'day'), name='class_daily_usage_unique'),
        ),
        migrations.AddIndex(
            model_name='rosterversion',
            index=models.Index(fields=['inclass', 'effective_term_start'], name='roster_class_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='rosterversion',
            constraint=models.UniqueConstraint(fields=('student', 'effective_term_start'), name='roster_student_term_unique'),
        ),
        migrations.AddConstraint(
            model_name='ownertermpolicy',
            constraint=models.UniqueConstraint(fields=('owner', 'term_key'), name='owner_term_policy_unique'),
        ),
        migrations.AddConstraint(
            model_name='classterm',
            constraint=models.UniqueConstraint(fields=('inclass', 'term_key'), name='class_term_unique'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('actor_key', 'scope', 'key'), name='submission_identity_scope_key_unique'),
        ),
        migrations.RunPython(preserve_legacy),
    ]
