# Generated by Django 5.2.17 on 2026-09-23 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_duxing_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeLoginGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_digest', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='managecode',
            field=models.CharField(default='!', max_length=128, verbose_name='旧班级密码（停用）'),
        ),
        migrations.CreateModel(
            name='CommitteeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('password', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('auth_version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_accounts', to='manage.class')),
            ],
        ),
    ]
