# Generated by Django 5.2.17 on 2026-09-24 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_configurable_scores_and_account_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringpolicyversion',
            name='average_decimal_places',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddConstraint(
            model_name='scoringpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('average_decimal_places__gte', 0), ('average_decimal_places__lte', 4)), name='policy_average_decimal_places_range'),
        ),
    ]
