# Generated by Django 5.2.17 on 2026-09-23 00:57

import django.core.validators
import hashlib
import manage.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def assign_prefixes(apps, schema_editor):
    Classroom=apps.get_model('manage','Class')
    Account=apps.get_model('manage','CommitteeAccount')
    alias=schema_editor.connection.alias
    used=set()
    prefixes={}
    for classroom in Classroom.objects.using(alias).order_by('id'):
        for attempt in range(65536):
            prefix=hashlib.sha256(f'duxing.class:{classroom.pk}:{attempt}'.encode()).hexdigest()[:4]
            if prefix not in used:
                break
        else:
            raise RuntimeError('No unique four-character committee prefix remains.')
        used.add(prefix);prefixes[classroom.pk]=prefix
        Classroom.objects.using(alias).filter(pk=classroom.pk).update(committee_prefix=prefix)
    accounts=list(Account.objects.using(alias).order_by('id').values('id','inclass_id','username','auth_version','revision'))
    # Stage names outside the accepted alphabet, avoiding collisions between an
    # old short username and another account's new complete username.
    for account in accounts:
        Account.objects.using(alias).filter(pk=account['id']).update(username=f'~migration:{account["id"]}')
    for account in accounts:
        Account.objects.using(alias).filter(pk=account['id']).update(
            username=prefixes[account['inclass_id']]+'.'+account['username'],
            auth_version=account['auth_version']+1,revision=account['revision']+1)
    # Existing hashes cannot be decrypted. No plaintext credential is invented;
    # an owner reset provisions the encrypted copy on demand. Audit is untouched.


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_named_committee_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='committee_prefix',
            field=models.CharField(editable=False, max_length=4, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='committeeaccount',
            name='credential_ciphertext',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='scoringpolicyversion',
            name='base_score',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='scoringpolicyversion',
            name='maximum_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='scoringpolicyversion',
            name='minimum_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='committeeaccount',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.RunPython(assign_prefixes),
        migrations.AlterField(
            model_name='class',
            name='committee_prefix',
            field=models.CharField(default=manage.models.committee_prefix, editable=False, max_length=4, unique=True),
        ),
        migrations.AddConstraint(
            model_name='scoringpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('base_score__gte', 0), ('base_score__lte', Decimal('999999.99')), ('minimum_score__gte', 0), ('minimum_score__lte', Decimal('999999.99')), models.Q(('maximum_score__isnull', True), models.Q(('maximum_score__gte', 0), ('maximum_score__lte', Decimal('999999.99'))), _connector='OR')), name='policy_monthly_range'),
        ),
        migrations.AddConstraint(
            model_name='scoringpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_score__lte', models.F('base_score')), models.Q(('maximum_score__isnull', True), ('base_score__lte', models.F('maximum_score')), _connector='OR')), name='policy_monthly_order'),
        ),
    ]
