# Generated by Django 5.2.17 on 2026-09-24 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0008_activity_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerLoginGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_digest', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('first_failure_at', models.FloatField(default=0)),
                ('blocked_until', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='committeeloginguard',
            name='first_failure_at',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PublicClassReportLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('token_ciphertext', models.TextField(editable=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_report_link', to='manage.class')),
            ],
        ),
    ]
