# Generated by Django 5.2.17 on 2026-09-24 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0009_public_reports_login_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='report_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CurrentClassReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_key', models.CharField(blank=True, max_length=16)),
                ('month_key', models.CharField(max_length=7)),
                ('source_revision', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('payload_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_public_report', to='manage.class')),
            ],
        ),
    ]
